// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-layout/internal/server"
	"gin-layout/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp() (*gin.Engine, func(), error) {
	greeterService := service.NewGreeterService()
	engine := server.NewHTTPServer(greeterService)
	return engine, func() {
	}, nil
}
